if(EXISTS "C:/Users/Asus/OneDrive/Desktop/ProgettoPCS/Projects/build-Raffinamento-Desktop-Release/raffinamento_test[1]_tests.cmake")
  include("C:/Users/Asus/OneDrive/Desktop/ProgettoPCS/Projects/build-Raffinamento-Desktop-Release/raffinamento_test[1]_tests.cmake")
else()
  add_test(raffinamento_test_NOT_BUILT raffinamento_test_NOT_BUILT)
endif()
